name: truck_scale
description: Truck Scale desktop app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-170.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # database
  cupertino_icons: ^1.0.2
  drift: ^1.7.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  shared_preferences: ^2.0.15
  # bloc
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  #styles
  google_fonts: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

